services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Oksana2lucky\WarehouseBundle\:
    resource: '../../'
    exclude: '../src/{DependencyInjection,Entity,Tests}'

  oksana2lucky_warehouse.service_import_fileResource:
    class: Oksana2lucky\WarehouseBundle\Import\FileResource
    arguments:
      - '@Oksana2lucky\WarehouseBundle\Import\Reader\CSVReader'

  oksana2lucky_warehouse.service_import_importer:
    class: Oksana2lucky\WarehouseBundle\Import\Importer
    arguments:
      - '@oksana2lucky_warehouse.service_import_fileResource'